export const EMPLOYEE_LIST_REQUEST = "EMPLOYEE_LIST_REQUEST";
export const EMPLOYEE_LIST_SUCCESS = "EMPLOYEE_LIST_SUCCCESS";
export const EMPLOYEE_LIST_FAIL = "EMPLOYEE_LIST_FAIL";

export const EMPLOYEE_SAVE_REQUEST = "EMPLOYEE_SAVE_REQUEST";
export const EMPLOYEE_SAVE_SUCCESS = "EMPLOYEE_SAVE_SUCCCESS";
export const EMPLOYEE_SAVE_FAIL = "EMPLOYEE_SAVE_FAIL";
